- hosts: localhost #, fedora, ubuntu
  vars:
    in_podman: false

  roles:
  - dev/ansible-role-Packer
  # - UniInc.Packer

# Some repos like 'chef/bento' have their own Builder install script, and this role can be skipped if using those
  # - Builder/default
